src/Entity/Commande.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\CommandeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_cmd;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $paiement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $etat;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCmd(): ?\DateTimeInterface
    {
        return $this->date_cmd;
    }

    public function setDateCmd(?\DateTimeInterface $date_cmd): self
    {
        $this->date_cmd = $date_cmd;

        return $this;
    }

    public function getPaiement(): ?string
    {
        return $this->paiement;
    }

    public function setPaiement(string $paiement): self
    {
        $this->paiement = $paiement;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }
}

src/Form/CommandeType.php
<?php

namespace App\Form;

use App\Entity\Commande;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_cmd')
            ->add('paiement')
            ->add('etat')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

src/Controller/CommandeController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Form\CommandeType;
use App\Repository\CommandeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/commande")
 */
class CommandeController extends AbstractController
{
    /**
     * @Route("/", name="commande_index", methods={"GET"})
     */
    public function index(CommandeRepository $commandeRepository): Response
    {
        return $this->render('commande/index.html.twig', [
            'commandes' => $commandeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="commande_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $commande = new Commande();
        $form = $this->createForm(CommandeType::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($commande);
            $entityManager->flush();

            return $this->redirectToRoute('commande_index');
        }

        return $this->render('commande/new.html.twig', [
            'commande' => $commande,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commande_show", methods={"GET"})
     */
    public function show(Commande $commande): Response
    {
        return $this->render('commande/show.html.twig', [
            'commande' => $commande,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="commande_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Commande $commande): Response
    {
        $form = $this->createForm(CommandeType::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('commande_index');
        }

        return $this->render('commande/edit.html.twig', [
            'commande' => $commande,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commande_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Commande $commande): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commande->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($commande);
            $entityManager->flush();
        }

        return $this->redirectToRoute('commande_index');
    }
}

templates/commande/_delete_form.html.twig
<form method="post" action="{{ path('commande_delete', {'id': commande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" value="DELETE" name="_method">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
    <button class="btn btn-danger "> <i class="fas fa-trash"></i></button>
</form>

templates/commande/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/commande/edit.html.twig
{% extends 'home/index.html.twig' %}
{% block title %}Edit commande{% endblock %}

{% block body %}
<div class="container-fluid">
    <h1>Edit commande</h1>

    {{ include('commande/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('commande_index') }}">Retour </a>

    {{ include('commande/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/commande/index.html.twig
{% extends 'home/index.html.twig' %}

{% block title %}commande index{% endblock %}
{% block body %}
<div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Table commande</h1>
          <p class="mb-4">Pour ajouter un nouveau article cliquer ici 
           <a href="{{ path('commande_new') }}" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-check"></i>
                    </span>
                    <span class="text">Ajouter un commande</span>
                  </a>
 <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">liste des commandes</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
           <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_cmd</th>
                <th>Paiement</th>
                <th>Etat</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
                <td>{{ commande.id }}</td>
                <td>{{ commande.dateCmd ? commande.dateCmd|date('Y-m-d') : '' }}</td>
                <td>{{ commande.paiement }}</td>
                <td>{{ commande.etat }}</td>
                <td>
                  <a href="{{ path('commande_show', {'id': commande.id}) }}">Afficher ||</a> 
                    <a href="{{ path('commande_edit', {'id': commande.id}) }}">Modifier</a>
                    {{ include('commande/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

              </div>
            </div>
          </div>

        </div>
   
{% endblock %}
            

templates/commande/new.html.twig
{% extends 'home/index.html.twig' %}

{% block title %}New commande{% endblock %}

{% block body %}
<div class="container-fluid">

 <h1 class="h3 mb-2 text-gray-800">Ajouter un commande</h1> <br>
           <a href="{{ path('commande_index') }}" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-check"></i>
                    </span>
                    <span class="text"> Retour à la liste commande</span>
                  </a>  <br>
       <div class="card shadow mb-4">
                        <div class="card-body">

    {{ include('commande/_form.html.twig') }}
</div></div></div>
{% endblock %}

templates/commande/show.html.twig
{% extends 'home/index.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
<div class="container-fluid">

<h1 class="h3 mb-2 text-gray-800">Détails d'un produit</h1> <br>
           <a href="{{ path('produit_index') }}" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-check"></i>
                    </span>
                    <span class="text"> Retour à la liste produit</span>
                  </a>  <br>
       <div class="card shadow mb-4">
                        <div class="card-body">


   <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commande.id }}</td>
            </tr>
            <tr>
                <th>Date_cmd</th>
                <td>{{ commande.dateCmd ? commande.dateCmd|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Paiement</th>
                <td>{{ commande.paiement }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ commande.etat }}</td>
            </tr>
        </tbody>
    </table>
<div class="row">
<div class="col-1">
    <a class="btn btn-primary" href="{{ path('produit_edit', {'id': produit.id}) }}">Modifier</a>
</div><div class="col-1">
    {{ include('produit/_delete_form.html.twig') }}
    </div>
</div>
</div>
{% endblock %}