src/Entity/Promotion.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\PromotionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass=PromotionRepository::class)
 */
class Promotion
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_fin;

    /**
     * @ORM\Column(type="integer")
     */
    private $reduction;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getReduction(): ?int
    {
        return $this->reduction;
    }

    public function setReduction(int $reduction): self
    {
        $this->reduction = $reduction;

        return $this;
    }
}

src/Form/PromotionType.php
<?php

namespace App\Form;

use App\Entity\Promotion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PromotionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_debut')
            ->add('date_fin')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Promotion::class,
        ]);
    }
}

src/Controller/PromotionController.php
<?php

namespace App\Controller;

use App\Entity\Promotion;
use App\Form\PromotionType;
use App\Repository\PromotionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/promotion")
 */
class PromotionController extends AbstractController
{
    /**
     * @Route("/", name="promotion_index", methods={"GET"})
     */
    public function index(PromotionRepository $promotionRepository): Response
    {
        return $this->render('promotion/index.html.twig', [
            'promotions' => $promotionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="promotion_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $promotion = new Promotion();
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($promotion);
            $entityManager->flush();

            return $this->redirectToRoute('promotion_index');
        }

        return $this->render('promotion/new.html.twig', [
            'promotion' => $promotion,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="promotion_show", methods={"GET"})
     */
    public function show(Promotion $promotion): Response
    {
        return $this->render('promotion/show.html.twig', [
            'promotion' => $promotion,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="promotion_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Promotion $promotion): Response
    {
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('promotion_index');
        }

        return $this->render('promotion/edit.html.twig', [
            'promotion' => $promotion,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="promotion_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Promotion $promotion): Response
    {
        if ($this->isCsrfTokenValid('delete'.$promotion->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($promotion);
            $entityManager->flush();
        }

        return $this->redirectToRoute('promotion_index');
    }
}

templates/promotion/_delete_form.html.twig
<form method="post" action="{{ path('promotion_delete', {'id': promotion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" class="btn btn-danger btn-circle" name="_method">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ promotion.id) }}">
    <button class="btn btn-danger "> <i class="fas fa-trash"></i></button>
</form>

templates/promotion/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/promotion/edit.html.twig
{% extends 'home/index.html.twig' %}
{% block title %}Edit promotion{% endblock %}

{% block body %}
<div class="container-fluid">
    <h1>Edit promotion</h1>

    {{ include('promotion/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('promotion_index') }}">Retour </a>

    {{ include('promotion/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/promotion/index.html.twig
{% extends 'home/index.html.twig' %}

{% block title %}promotion index{% endblock %}
{% block body %}
<div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Table promotion</h1>
          <p class="mb-4">Pour ajouter un nouveau article cliquer ici 
           <a href="{{ path('promotion_new') }}" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-check"></i>
                    </span>
                    <span class="text">Ajouter une promotion</span>
                  </a>
 <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">liste des promotions</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
         
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for promotion in promotions %}
            <tr>
                <td>{{ promotion.id }}</td>
                <td>{{ promotion.dateDebut ? promotion.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ promotion.dateFin ? promotion.dateFin|date('Y-m-d') : '' }}</td>
                <td>
                        <a href="{{ path('promotion_show', {'id': promotion.id}) }}">Afficher ||</a> 
                    <a href="{{ path('promotion_edit', {'id': promotion.id}) }}">Modifier</a>
                    {{ include('promotion/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

              </div>
            </div>
          </div>

        </div>
   
{% endblock %}
            

templates/promotion/new.html.twig
{% extends 'home/index.html.twig' %}

{% block title %}Nouvelle promotion{% endblock %}

{% block body %}
<div class="container-fluid">

 <h1 class="h3 mb-2 text-gray-800">Ajouter une promotion</h1> <br>
           <a href="{{ path('promotion_index') }}" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-check"></i>
                    </span>
                    <span class="text"> Retour à la liste promotion</span>
                  </a>  <br>
       <div class="card shadow mb-4">
                        <div class="card-body">

    {{ include('promotion/_form.html.twig') }}
</div></div></div>
{% endblock %}

templates/promotion/show.html.twig
{% extends 'home/index.html.twig' %}

{% block title %}promotion{% endblock %}

{% block body %}
<div class="container-fluid">

<h1 class="h3 mb-2 text-gray-800">Détails d'une promotion</h1> <br>
           <a href="{{ path('promotion_index') }}" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-check"></i>
                    </span>
                    <span class="text"> Retour à la liste promotion</span>
                  </a>  <br>
       <div class="card shadow mb-4">
                        <div class="card-body">


    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ promotion.id }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ promotion.dateDebut ? promotion.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ promotion.dateFin ? promotion.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

<div class="row">
<div class="col-1">
    <a class="btn btn-primary" href="{{ path('promotion_edit', {'id': promotion.id}) }}">Modifier</a>
</div><div class="col-1">
    {{ include('promotion/_delete_form.html.twig') }}
    </div>
</div>
</div>
{% endblock %}